client_config_backend: settings
client_config:
  client_id: YOUR_GOOGLE_CLIENT_ID_HERE
  client_secret: YOUR_GOOGLE_CLIENT_SECRET_HERE

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
